baseURL = 'https://prokorpio.github.io/'
languageCode = 'en-us'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params.author]
  name = "Chris: Uy / Hi / Ciao!"
  #avatar = "/avatar.png"
  #avatarSize = "size-m"
  #email = "christopher.sanchez@studenti.unitn.it"
  #avatarFirst = false
#
[[params.social]]
key = 0
name = "email"
url = "christopher.sanchez@studenti.unitn.it"
aria = "My e-Mail Address"

[params]
user = "prokorpio"
hostname = "github.io"
openLinksInNewTab = true
displayDateFormat = "2006-01-02"
footerHtml = 'site under construction ✌️😅'


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.styles]
color = "orange"

[pagination]
pagerSize = 3

# Global metadata display settings
# Each can be overridden in individual post frontmatter
showMetadata = true       # Master switch for all metadata display
showPublishedDate = true  # Show published date on post page
showReadingTime = true    # Show reading time on post page
showTags = true           # Show tags on post page
showAuthors = true        # Show authors on post page
showCategories = true     # Show categories on post page


