baseURL = 'https://prokorpio.github.io/'
languageCode = 'en-us'
theme = "hugo-theme-nightfall"
title = 'prokorpio@github.io'

[module]
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
pagerSize = 3

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
user = "prokorpio"
hostname = "github.io"

[params.author]
  name = "Chris"
  avatar = "/avatar.png"
  avatarSize = "size-m"
  email = "christopher.sanchez@studenti.unitn.it"
  avatarFirst = false

openLinksInNewTab = true
displayDateFormat = "2006-01-02"

# Global metadata display settings
# Each can be overridden in individual post frontmatter
showMetadata = true       # Master switch for all metadata display
showPublishedDate = true  # Show published date on post page
showReadingTime = true    # Show reading time on post page
showTags = true           # Show tags on post page
showAuthors = true        # Show authors on post page
showCategories = true     # Show categories on post page

[params.author]
  name = "Chris"  # Website and RSS feed author
  email = "christopher.sanchez@studenti.unitn.it"  # RSS feed email address

[[params.social]]
key = 0
name = "email"
url = "christopher.sanchez@studenti.unitn.it"
aria = "My e-Mail Address"

[params.styles]
color = "orange"

[params]
footerHtml = 'Hi guys!'
